language: python
python:
  - "3.6"

services:
  - postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=myapp.settings

install:
  - pip install -r requirements.txt

script:
  - python manage.py test