language: python
python:
  - "3.6"

services:
  - postgresql

env:
  - DJANGO=2.1

before_install:
  - export DJANGO_SETTINGS_MODULE=mysite.settings

install:
  - pip install -r requirements.txt

script:
  - python manage.py test