# Generated by Django 2.1.7 on 2019-04-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_product',
            name='img_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reg_product',
            name='nut_url',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reg_product',
            name='nutrition_grade',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reg_product',
            name='url',
            field=models.CharField(default='.', max_length=200),
            preserve_default=False,
        ),
    ]
