# Generated by Django 2.1.7 on 2019-04-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reg_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_product',
            name='nut_url',
        ),
        migrations.RemoveField(
            model_name='reg_product',
            name='url',
        ),
    ]
